#!/bin/bash
echo "CURRENTLY LOGGED USER : $USER"	
echo "LOGIN NAME : $LOGNAME"
echo "CURRENT SHELL : $SHELL"
echo "HOME DIRECTORY : $HOME"
echo "OPERATING SYSTEM : $OSTYPE"
echo "CURRENT PATH SETTING : $PATH"
echo "CURRENT WORKING DIRECTORY : "
pwd
echo "CURRENTLY LOGGED NUMBER OF USERS : " 
ps
